#pragma once
//引入所有监听文件
#include "QIPlayerAudioDataListener.h"
#include "QIPlayerAudioListener.h"
#include "QIPlayerAuthenticationListener.h"
#include "QIPlayerBiteRateListener.h"
#include "QIPlayerBufferingListener.h"
#include "QIPlayerCommandNotAllowListener.h"
#include "QIPlayerDownloadListener.h"
#include "QIPlayerFormatListener.h"
#include "QIPlayerFPSListener.h"
#include "QIPlayerMediaNetworkListener.h"
#include "QIPlayerProgressListener.h"
#include "QIPlayerQualityListener.h"
#include "QIPlayerSeekListener.h"
#include "QIPlayerRenderListener.h"
#include "QIPlayerSEIDataListener.h"
#include "QIPlayerShootVideoListener.h"
#include "QIPlayerSpeedListener.h"
#include "QIPlayerStateChangeListener.h"
#include "QIPlayerSteamListener.h"
#include "QIPlayerSubtitleListener.h"
#include "QIPlayerVideoDataListener.h"
#include "QIPlayerVideoDecodeListender.h"
#include "QIPlayerVideoFrameSizeChangeListener.h"

